INSERT ALL
INTO gg_team VALUES ('Cloud9', 'https://www.facebook.com/cloud9/', 'https://twitter.com/cloud9', 'https://www.youtube.com/user/C9ggTV', 'http://cloud9.gg/overwatch', null)
INTO gg_team VALUES ('EnVyus', 'https://www.facebook.com/TeamEnVyUs/', 'https://twitter.com/TeamEnVyUs', 'https://www.youtube.com/user/TeamEnVyUs', 'https://gg_teamenvyus.com/pages/overwatch', null)
INTO gg_team VALUES ('FaZe Clan', 'https://www.facebook.com/TheFaZeClan', 'https://twitter.com/FaZeClan', 'https://www.youtube.com/user/FaZeClan', null, null)
INTO gg_team VALUES ('NRG', 'https://www.facebook.com/NRGwin/', 'https://twitter.com/NRGgg', 'https://www.youtube.com/c/nrggg', 'http://www.nrg.gg/overwatch', null)
INTO gg_team VALUES ('Misfits', 'https://www.facebook.com/MisfitsGG/', 'https://twitter.com/misfitsgg', null, null, null)
INTO gg_team VALUES ('LG Loyal', 'https://www.facebook.com/LGLOYAL/', 'https://twitter.com/Luminosity', 'https://www.youtube.com/luminositygaming', null, null)
INTO gg_team VALUES ('Rogue', 'https://www.facebook.com/goingroguegg/', 'https://twitter.com/goingroguegg', 'https://www.youtube.com/roguegg', null, null)
INTO gg_team VALUES ('Lunatic Hai', 'https://www.facebook.com/lunatichai/', 'https://twitter.com/LunaticHai_YT', 'https://www.youtube.com/channel/UCQv4agxmCKzinBJDbFi8eVA', null, null)
INTO gg_team VALUES ('Selfless', 'https://www.facebook.com/SelflessGG/', 'https://twitter.com/selflessgg', 'https://www.youtube.com/channel/UCmpscN0VVPkyPVMoUwNTGZA', 'https://selfless.gg/overwatch/', null)
INTO gg_team VALUES ('Immortals', 'https://www.facebook.com/Immortalsgg/', 'https://twitter.com/immortals', 'https://www.youtube.com/c/immortalsgg', 'https://immortals.gg/gg_teams/Overwatch/', null)
INTO gg_team VALUES ('Blank Esports', 'https://www.facebook.com/BlankEsports/', 'https://twitter.com/blankoce', null, null, null)
INTO gg_team VALUES ('Runaway', null, null, null, null, null)
INTO gg_team VALUES ('Fnatic', 'https://www.facebook.com/fnatic/', 'https://twitter.com/fnatic', 'https://www.youtube.com/user/fnaticTV', 'http://www.fnatic.com/players/overwatch/', null)
INTO gg_team VALUES ('Ninjas in Pyjamas', 'https://www.facebook.com/NipGaming/', 'https://twitter.com/NiPGaming', 'https://www.youtube.com/user/NiPGamingOfficial', 'https://nip.gl/players', null)
INTO gg_team VALUES ('Team Liquid', 'https://www.facebook.com/gg_teamliquid/', 'https://twitter.com/teamliquid', 'https://www.youtube.com/channel/UCLSWNf28X3mVTxTT3_nLCcw', 'https://www.teamliquidpro.com/players#overwatch', null)
INTO gg_team VALUES ('Renegades', 'https://www.facebook.com/TeamRNG/', 'https://twitter.com/renegades', 'https://www.youtube.com/c/Renegades', 'hhttps://www.renegadespro.com/pages/overwatch', null)
SELECT * FROM dual;

--VALUES(hero_stats_id, hero_name)
INSERT ALL
INTO gg_hero_stats VALUES (1, 'Genji')
INTO gg_hero_stats VALUES (2, 'McCree')
INTO gg_hero_stats VALUES (3, 'Pharah')
INTO gg_hero_stats VALUES (4, 'Reaper')
INTO gg_hero_stats VALUES (5, 'Soldier: 76')
INTO gg_hero_stats VALUES (6, 'Sombra')
INTO gg_hero_stats VALUES (7, 'Tracer')
INTO gg_hero_stats VALUES (8, 'Bastion')
INTO gg_hero_stats VALUES (9, 'Hanzo')
INTO gg_hero_stats VALUES (10, 'Junkrat')
INTO gg_hero_stats VALUES (11, 'Mei')
INTO gg_hero_stats VALUES (12, 'Torbjorn')
INTO gg_hero_stats VALUES (13, 'Widowmaker')
INTO gg_hero_stats VALUES (14, 'D.Va')
INTO gg_hero_stats VALUES (15, 'Orisa')
INTO gg_hero_stats VALUES (16, 'Reinhardt')
INTO gg_hero_stats VALUES (17, 'Roadhog')
INTO gg_hero_stats VALUES (18, 'Winston')
INTO gg_hero_stats VALUES (19, 'Zarya')
INTO gg_hero_stats VALUES (20, 'Ana')
INTO gg_hero_stats VALUES (21, 'Lucio')
INTO gg_hero_stats VALUES (22, 'Mercy')
INTO gg_hero_stats VALUES (23, 'Symmetra')
INTO gg_hero_stats VALUES (24, 'Zenyatta')
SELECT * FROM dual;
